"""The GLE Variable Comment Exporter's routes: request in, response out.

Seven of them. `/` and `/index.html` serve the landing page, `/state` answers
what this visitor has open, `/download` streams a generated file out of the
session's own directories, and the three POSTs are the tool itself --
`/select-rdb` picks an RDB out of the project library, `/export` builds the
spreadsheet, `/import` takes it back and writes a new RDB.

The `/import` upload control is this tool's own, deliberately: the spreadsheet
it takes is one this tool produced, not a project input, so it is not behind
the library picker. What both routes WRITE does enter the library, through
`publish_output`.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from urllib.parse import quote, urlparse

from sellib import rdb as rdb_loader

from pacct import library as filelib
from pacct.paths import is_within
from pacct.web.gle_exporter import load_template
from pacct.web.gle_exporter.export import (
    apply_xlsx_updates_to_rdb,
    build_xlsx_for_selections,
    parse_xlsx_to_updates,
)
from pacct.web.gle_exporter.model import extract_port_instances_from_gle
from pacct.web.gle_exporter.state import SessionState, state_payload
from pacct.web.rdb_write import (
    with_suffix_before_ext as _with_suffix_before_ext,
)
from pacct.web.session import SessionHandler

_logger = logging.getLogger(__name__)

_XLSX_MAX_BYTES = 50 * 1024 * 1024


# -----------------------------------------------------------------------------
# HTML
# -----------------------------------------------------------------------------

LANDING_HTML = load_template("landing.html")

# The numbered navigation is the same on the nine screens -- lives in theme.py.


# -----------------------------------------------------------------------------
# Server
# -----------------------------------------------------------------------------

def build_gle_exporter_handler(logger: logging.Logger, sessions) -> type:
    """Return the GLE Variable Comment Exporter handler class.

    Opens no server: serving is done by the single dispatcher of
    `pacct.web.mount`, which mounts this handler at `/gle-exporter/`. State
    and files are per session (`self.sess()` / `self.sdir()`), not per
    process.
    """

    class Handler(SessionHandler):
        session_key = "gle-exporter"
        state_factory = SessionState
        server_sessions = sessions

        def do_GET(self):
            parsed = urlparse(self.path)
            path = parsed.path
            if path in ("/", "/index.html"):
                self._send(200, LANDING_HTML, "text/html; charset=utf-8")
                return
            if path == "/gle-state":
                self._send_json(200, {"ok": True})
                return
            if path == "/state":
                self._send_json(200, state_payload(self.sess()))
                return
            if path == "/download":
                from urllib.parse import parse_qs as _parse_qs
                qs = _parse_qs(parsed.query)
                file_param = (qs.get("file") or [""])[0]
                if not file_param:
                    self._send(400, "missing 'file' param", "text/plain")
                    return
                target = Path(file_param).resolve()
                # `rdbs` is gone: uploads now go to the content cache,
                # which is shared -- letting it into the sandbox would hand
                # one visitor the derived file generated by another.
                if not is_within(target, (self.sdir("out"), self.sdir("xlsx"))):
                    self._send(403, "path outside allowed roots", "text/plain")
                    return
                if not target.is_file():
                    self._send(404, "file not found", "text/plain")
                    return
                ext = target.suffix.lower()
                if ext == ".xlsx":
                    ctype = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
                else:
                    ctype = "application/octet-stream"
                # Streamed: an exported RDB is 40-140 MB, and `read_bytes()`
                # held all of it per concurrent download on a threaded server.
                # `send_file` also writes the RFC 5987 name -- these names come
                # from a DISPLAY name and carry accents, and `send_header`
                # encodes latin-1 strict, so a plain `filename="..."` with an
                # en-dash raises after the status line has gone out.
                self.send_file(target, ctype, download_name=target.name)
                return

            self._send(404, "not found", "text/plain")

        def do_POST(self):
            path = urlparse(self.path).path
            try:
                length = int(self.headers.get("Content-Length", "0"))
            except ValueError:
                length = 0

            if path == "/select-rdb":
                # The body of the old /rdb-upload, from `process_upload`
                # onward: the file was already received and extracted in
                # /files/.
                payload = self._read_json_body()
                sha = (payload.get("sha256") or "").strip()
                lib = filelib.library_for(sessions, self.require_session())
                with self.require_session().lock:
                    chosen = lib.get(sha)
                if chosen is None or chosen.kind != filelib.KIND_RDB:
                    self._send_json(404, {
                        "error": "Arquivo não está mais no projeto."})
                    return
                info = chosen.require_rdb()
                logger.info("[gle-exporter] RDB '%s' (%s) escolhido; "
                            "%d relé(s) com GLE",
                            info.display_name, info.sha256[:16],
                            len(info.relays))
                st = self.sess()
                with self.require_session().lock:
                    st.rdb = info
                self._send_json(200, state_payload(self.sess()))
                return

            if path == "/export":
                job = self.job()
                job.stage("Lendo selecao", 0)
                body = self.rfile.read(length) if length > 0 else b"{}"
                try:
                    payload = json.loads(body or b"{}")
                    selections = payload.get("selections", [])
                except (json.JSONDecodeError, TypeError):
                    self._send_json(400, {"error": "bad request"})
                    return
                if not isinstance(selections, list) or not selections:
                    self._send_json(400, {"error": "selections vazia"})
                    return
                with self.require_session().lock:
                    rdb = self.sess().rdb
                if rdb is None:
                    self._send_json(409, {"error": "RDB nao carregado"})
                    return
                from sellib.models import relay_models as _rm
                model_cache: dict[str, object] = {}
                def _model_for(relay_name: str):
                    if relay_name in model_cache:
                        return model_cache[relay_name]
                    r_entry = next(
                        (r for r in rdb.relays if r.name == relay_name), None,
                    )
                    m = (_rm.lookup(r_entry.model)
                         if (r_entry and r_entry.model) else None)
                    model_cache[relay_name] = m
                    return m

                resolved: list[dict] = []
                for sel in selections:
                    if not isinstance(sel, dict):
                        continue
                    relay = str(sel.get("relay", "")).strip()
                    gle = str(sel.get("gle", "")).strip()
                    if not (relay and gle):
                        continue
                    gle_entry = rdb_loader.find_gle(rdb, relay, gle)
                    if gle_entry is None or not gle_entry.fs_path.is_file():
                        continue
                    resolved.append({
                        "relay": relay, "gle": gle,
                        "gle_path": gle_entry.fs_path,
                        "relay_model": _model_for(relay),
                    })
                if not resolved:
                    self._send_json(422, {"error": "nenhuma selecao valida"})
                    return
                try:
                    xlsx_bytes = build_xlsx_for_selections(resolved)
                except Exception as e:
                    logger.exception("falha gerando xlsx: %s", e)
                    self._send_json(500, {"error": str(e)})
                    return
                out_name = _with_suffix_before_ext(
                    Path(rdb.display_name), "_gle_comments",
                ).with_suffix(".xlsx").name
                job.stage("Gravando planilha", 90)
                out_path = (self.sdir("xlsx") / out_name).resolve()
                try:
                    out_path.write_bytes(xlsx_bytes)
                except OSError as e:
                    self._send_json(500, {"error": f"falha ao salvar xlsx: {e}"})
                    return
                # Count the exported ports to show in the summary.
                total_ports = 0
                for sel in resolved:
                    total_ports += len(extract_port_instances_from_gle(
                        sel["gle_path"], relay_model=sel.get("relay_model"),
                    ))
                logger.info(
                    "[gle-exporter] export: %d aba(s), %d porta(s) -> %s",
                    len(resolved), total_ports, out_name,
                )
                # The spreadsheet enters the library too: no tool selects
                # it (nobody asks for `?kind=xlsx`), but this way it can be
                # downloaded again later from one single place, instead of
                # only from the tab that happened to generate it.
                project = self.publish_output(out_path, "GLE Exporter",
                                              job=job, logger=logger)
                job.finish("Planilha gerada")
                self._send_json(200, {
                    "ok": True,
                    "output_name": out_name,
                    "project_file": project,
                    "download_url": self.mount_prefix + "/download?file=" + quote(str(out_path), safe=""),
                    "selections_count": len(resolved),
                    "total_ports": total_ports,
                })
                return

            if path == "/import":
                job = self.job()
                job.stage("Recebendo planilha", 0)
                if length <= 0:
                    self._send_json(400, {"error": "empty upload"})
                    return
                if length > _XLSX_MAX_BYTES:
                    self._send_json(413, {
                        "error": f"xlsx grande demais (limite "
                                 f"{_XLSX_MAX_BYTES // (1024*1024)} MB)",
                    })
                    return
                with self.require_session().lock:
                    rdb = self.sess().rdb
                if rdb is None:
                    self._send_json(409, {"error": "RDB nao carregado"})
                    return
                xlsx_bytes = self.rfile.read(length)
                try:
                    updates = parse_xlsx_to_updates(xlsx_bytes)
                except Exception as e:
                    logger.exception("falha parseando xlsx: %s", e)
                    self._send_json(422, {"error": f"xlsx invalido: {e}"})
                    return
                if not updates:
                    self._send_json(422, {
                        "error": "nenhum update valido encontrado no xlsx "
                                 "(verifique A1='Relay:' e A2='GLE:' em cada aba)",
                    })
                    return
                # The source RDB lives in the content cache, which is
                # shared; the derived output belongs to this session.
                out_path = self.sdir("out") / _with_suffix_before_ext(
                    Path(rdb.display_name), "_gle_comments_updated",
                ).name
                try:
                    result = apply_xlsx_updates_to_rdb(
                        rdb_info=rdb, xlsx_updates=updates, output_path=out_path,
                        job=job,
                    )
                except Exception as e:
                    logger.exception("falha aplicando updates: %s", e)
                    self._send_json(500, {"error": str(e)})
                    return
                if not result.get("ok"):
                    # All-or-nothing: no selection was written, so there
                    # is no file to download nor to publish into the library.
                    msg = result.get("error") or "Falha ao aplicar as alterações."
                    job.fail(msg)
                    logger.warning("[gle-exporter] import abortado: %s", msg)
                    self._send_json(400, result)
                    return
                out_abs = Path(result["output_path"]).resolve()
                # The RDB with the comments applied is the next tool's
                # input: it enters the project library, already extracted.
                result["project_file"] = self.publish_output(
                    out_abs, "GLE Exporter", job=job, logger=logger)
                job.finish("RDB atualizado")
                result["download_url"] = self.mount_prefix + "/download?file=" + quote(str(out_abs), safe="")
                result["output_name"] = out_abs.name
                logger.info(
                    "[gle-exporter] import: %d (relay,gle) processado(s), "
                    "%d ok, %d falha -> %s",
                    len(updates), result.get("succeeded", 0),
                    result.get("failed", 0), out_abs.name,
                )
                self._send_json(200, result)
                return

            self._send(404, "not found", "text/plain")

    return Handler
