"""The progress bar: a job registry on the server, and the tag that reaches
its runtime on the client.

**The runtime itself left this file in B17b.** It was 219 lines / 8,546 bytes
of JavaScript in a raw string here, injected inline into every `text/html`
response, and nothing checked a byte of it -- no lint, no types, no syntax
check, no test; a typo was found by a browser, on every screen at once. It is
`frontend/src/lib/progress.ts` now, built like every other client file, and
what stays here is the registry, the `JobReporter` sugar, the `/progress`
response and the one tag that loads it.

This toolkit handles RDBs of 40-140 MB. Uploading one used to be a frozen
screen reading "Enviando RDB..." for tens of seconds -- with no way to tell
whether it was moving, stuck, or nearly done. Two phases need feedback, and
the browser knows about only one of them by itself:

1. **Upload** (browser -> server). `fetch()` does not expose upload progress;
   `XMLHttpRequest.upload.onprogress` does. That is why the client runtime
   uses XHR for uploads -- it is the only way to get bytes sent / bytes total.

2. **Processing** (inside the server). Once the body has arrived there are
   still seconds of OLE extraction, relay reading, diffing and SVG rendering.
   The browser cannot know any of that, so the server publishes the stage into
   an in-memory registry and the client polls `/progress?job=<id>`.

The `job_id` is generated by the client and travels in the POST's `X-Job-Id`
header. Because the server is a `ThreadingHTTPServer`, the progress GET is
answered in parallel while the POST is still running -- which is what makes
phase 2 work without SSE or a WebSocket.

The `/progress` route is served by the dispatcher, so it works for every
mounted tool without any of them declaring the route.
"""

from __future__ import annotations

import json
import threading
import time

# A job dies after this long without an update. That covers a client
# vanishing mid-flight (a closed tab) without stranding an entry for ever.
_JOB_TTL_SECONDS = 600

# Accept only the shape the client generates: arbitrary text as a key in a
# dictionary that grows without bound is not a good idea.
_MAX_JOB_ID = 64


class ProgressRegistry:
    """Each job's current stage, by id. Written by the handler, read by the GET."""

    def __init__(self):
        self._jobs: dict[str, dict] = {}
        self._lock = threading.Lock()

    def set(self, job_id: str, stage: str, pct: float | None = None,
            done: bool = False, error: str | None = None) -> None:
        """Publica o estagio atual. `pct` e' 0..100, ou None se indeterminado."""
        if not job_id or len(job_id) > _MAX_JOB_ID:
            return
        now = time.time()
        with self._lock:
            self._jobs[job_id] = {
                "stage": stage,
                "pct": pct,
                "done": done,
                "error": error,
                "ts": now,
            }
            # Prune old jobs on the way through a write -- this does not
            # need a thread of its own.
            if len(self._jobs) > 32:
                cutoff = now - _JOB_TTL_SECONDS
                for k in [k for k, v in self._jobs.items() if v["ts"] < cutoff]:
                    self._jobs.pop(k, None)

    def get(self, job_id: str) -> dict:
        with self._lock:
            job = self._jobs.get(job_id)
            return dict(job) if job else {"stage": "", "pct": None,
                                          "done": False, "error": None}

    def finish(self, job_id: str, stage: str = "Pronto") -> None:
        self.set(job_id, stage, pct=100.0, done=True)

    def fail(self, job_id: str, error: str) -> None:
        self.set(job_id, "Falhou", pct=None, done=True, error=error)

    def drop(self, job_id: str) -> None:
        with self._lock:
            self._jobs.pop(job_id, None)


# One registry per process. Job ids are random and client-generated, so there
# is no need to partition them per session.
REGISTRY = ProgressRegistry()


class JobReporter:
    """Sugar for reporting a job's stages from inside a handler.

    Becomes a no-op when the client sent no `X-Job-Id` (a curl call, say), so
    handler code never has to check for one.
    """

    __slots__ = ("job_id", "registry")

    def __init__(self, job_id: str | None, registry: ProgressRegistry = REGISTRY):
        self.job_id = job_id or ""
        self.registry = registry

    def __bool__(self) -> bool:
        return bool(self.job_id)

    def stage(self, text: str, pct: float | None = None) -> None:
        if self.job_id:
            self.registry.set(self.job_id, text, pct)

    def fraction(self, text: str, done: int, total: int) -> None:
        """A stage whose percentage is derived from `done/total`."""
        if self.job_id and total > 0:
            self.registry.set(self.job_id, text, 100.0 * done / total)

    def finish(self, text: str = "Pronto") -> None:
        if self.job_id:
            self.registry.finish(self.job_id, text)

    def fail(self, error: str) -> None:
        if self.job_id:
            self.registry.fail(self.job_id, error)


def progress_response(job_id: str) -> bytes:
    return json.dumps(REGISTRY.get(job_id)).encode("utf-8")


# -----------------------------------------------------------------------------
# Runtime do cliente
# -----------------------------------------------------------------------------

# A bar fixed to the top of the viewport, deliberately outside the document
# flow: the tools have different layouts, and this way none of them had to
# make room for it.
#
# The two phases split the bar: the upload occupies 0-60%, the server-side
# processing 60-100%. On a large RDB the two take comparable time, so mapping
# the upload onto 0-100% would falsely read as "finished" with half the work
# still to do.
# Absolute, and it resolves under every mount: `mount.py` answers `/static/...`
# at the root AND behind any prefix -- the same reason `library/client.py`
# points at an absolute path for `SelLibrary`.
PROGRESS_JS_URL = "/static/js/lib/progress.js"

PROGRESS_TAG = f'<script src="{PROGRESS_JS_URL}"></script>\n'


def inject_progress_runtime(html: str) -> str:
    """Insert the bar's tag just before `</body>`, or at the end.

    **The position is the contract, and it did not move in B17b.** The tag goes
    exactly where the 219-line inline block used to go: immediately before
    `</body>`, which is AFTER the page's own `<script src>`. That ordering is
    what lets every tool leave `SelProgress` alone at the top level of its
    script -- and it is why the tag carries no `defer` and no `async`, either
    of which would let the page's own script run first and find it missing.

    It is a `<script src>` rather than the runtime itself since B17b: the
    JavaScript is `frontend/src/lib/progress.ts`, built to
    `web/static/js/lib/progress.js`. What that buys is that the file is linted,
    type-checked and diffable, which 219 lines inside a Python string never
    were. What it costs is one more request per HTML response, uncached
    (`mount.py` serves `.js` as `no-store`), and that price is stated here
    rather than discovered later.
    """
    idx = html.rfind("</body>")
    if idx == -1:
        return html + PROGRESS_TAG
    return html[:idx] + PROGRESS_TAG + html[idx:]
