"""The VB Updater's routes: request in, response out.

Five GET branches and five POST. `/` and `/index.html` serve the landing page,
`/vb-state` is the sentinel the dashboard pings to see the tool is up, `/state`
answers what this visitor has open, `/download` streams a generated file out of
the session's own directories, and `/compare` renders the comparison page.
`/select-rdb` and `/select-scd` pick a file out of the project library and run
the cross-match; `/apply` and `/apply-batch` write an RDB or an SCD; and
`/export-descriptions` and `/import-descriptions` are the spreadsheet round
trip.

The `/import-descriptions` upload control is this tool's own, deliberately: the
workbook it takes is one this tool produced, not a project input, so it does not
sit behind the library picker. What every one of the four writing routes
produces DOES enter the library, through `publish_output`.

Three routes build their output name from `st.scd_name` or `rdb.display_name`
and never from the file on disk, for the reason `state.py` records.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from urllib.parse import parse_qs, quote, unquote, urlparse

from sellib import rdb as rdb_loader

from pacct.paths import is_within
from pacct.web.project_files import library as filelib
from pacct.web.rdb_write import (
    with_suffix_before_ext as _with_suffix_before_ext,
)
from pacct.web.session import SessionHandler
from pacct.web.vb_updater import load_template
from pacct.web.vb_updater.export import (
    build_vb_descriptions_xlsx,
    parse_vb_descriptions_xlsx,
    update_rdb_with_scd_descs,
    update_rdb_with_scd_descs_batch,
    update_scd_with_descriptions_multi,
    update_scd_with_gle_comments,
)
from pacct.web.vb_updater.render import render_compare_page
from pacct.web.vb_updater.state import SessionState, maybe_match, state_payload

# Generous upload ceiling (used only by /import-descriptions, which takes
# the xlsx back -- the RDB and the SCD themselves come from the library).
_SCD_MAX_BYTES = 200 * 1024 * 1024

# Directory where the uploaded SCDs are saved. It lives in cache/ so it is
# gitignored automatically.
# Uploads and outputs live in cache/sessions/<sid>/ (see pacct.web.session).

# -----------------------------------------------------------------------------
# HTML
# -----------------------------------------------------------------------------

LANDING_HTML = load_template("landing.html")

# The numbered navigation is the same on the nine screens -- lives in theme.py.



# -----------------------------------------------------------------------------
# Server
# -----------------------------------------------------------------------------

def build_vb_updater_handler(logger: logging.Logger, sessions) -> type:
    """Return the VB Updater handler class.

    Opens no server: serving is done by the single dispatcher of
    `pacct.web.mount`, which mounts this handler at `/vb-updater/`. State and
    uploads are per session (`self.sess()` / `self.sdir()`), not per process.
    """

    class Handler(SessionHandler):
        session_key = "vb-updater"
        state_factory = SessionState
        server_sessions = sessions

        def do_GET(self):
            parsed = urlparse(self.path)
            path = parsed.path
            qs = parse_qs(parsed.query)

            if path in ("/", "/index.html"):
                self._send(200, LANDING_HTML, "text/html; charset=utf-8")
                return
            if path == "/vb-state":
                # Sentinel the home/dashboard uses to detect that this
                # tool is up.
                self._send_json(200, {"ok": True})
                return
            if path == "/state":
                self._send_json(200, state_payload(self.sess()))
                return
            if path == "/download":
                # Serves a file generated by /apply as a download. Sandboxed
                # to the session's own directories to prevent
                # path traversal.
                file_param = (qs.get("file") or [""])[0]
                if not file_param:
                    self._send(400, "missing 'file' param", "text/plain")
                    return
                target = Path(file_param).resolve()
                # `rdbs` is gone: uploads now go to the content cache,
                # which is shared -- letting it into the sandbox would hand
                # one visitor the derived file generated by another.
                if not is_within(target, (self.sdir("out"), self.sdir("scd"))):
                    self._send(403, "path outside allowed roots", "text/plain")
                    return
                if not target.is_file():
                    self._send(404, "file not found", "text/plain")
                    return
                ext = target.suffix.lower()
                if ext == ".rdb":
                    ctype = "application/octet-stream"
                elif ext == ".xlsx":
                    ctype = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
                else:
                    ctype = "application/xml"
                # Streamed, and RFC 5987 named -- see `SessionHandler.send_file`.
                self.send_file(target, ctype, download_name=target.name)
                return
            if path == "/compare":
                relay = (qs.get("relay") or [""])[0]
                ied = (qs.get("ied") or [""])[0]
                gle = (qs.get("gle") or [""])[0]
                with self.require_session().lock:
                    st = self.sess()
                    rdb = st.rdb
                    scd_path = st.scd_path
                if rdb is None or scd_path is None:
                    self._send(409, "RDB ou SCD nao carregado", "text/plain")
                    return
                entry = rdb_loader.find_gle(rdb, relay, gle)
                if entry is None or not entry.fs_path.is_file():
                    self._send(404, f"GLE {gle!r} nao encontrado para o rele {relay!r}",
                               "text/plain")
                    return
                try:
                    html = render_compare_page(
                        rdb_relay=relay, ied_name=ied, gle_name=gle,
                        gle_path=entry.fs_path, scd_path=scd_path,
                    )
                except Exception as e:
                    logger.exception("falha renderizando comparacao: %s", e)
                    self._send(500, f"falha: {e}", "text/plain")
                    return
                self._send(200, html, "text/html; charset=utf-8")
                return

            self._send(404, "not found", "text/plain")

        def do_POST(self):
            path = urlparse(self.path).path
            try:
                length = int(self.headers.get("Content-Length", "0"))
            except ValueError:
                length = 0

            if path == "/apply":
                job = self.job()
                job.stage("Aplicando alteracoes", 10)
                body = self.rfile.read(length) if length > 0 else b"{}"
                try:
                    payload = json.loads(body or b"{}")
                    direction = str(payload.get("direction", "")).strip()
                    relay = str(payload.get("relay", "")).strip()
                    ied = str(payload.get("ied", "")).strip()
                    gle = str(payload.get("gle", "")).strip()
                except (json.JSONDecodeError, TypeError):
                    self._send_json(400, {"error": "bad request"})
                    return
                if direction not in ("scd-to-gle", "gle-to-scd"):
                    self._send_json(400, {"error": "direction invalida"})
                    return
                with self.require_session().lock:
                    st = self.sess()
                    rdb = st.rdb
                    scd_path = st.scd_path
                    # The DISPLAY name, not the file's: the library keeps
                    # the SCD as `<sha12>.scd`, so deriving the output from
                    # the path named the user's file
                    # "72586aeda11e_comments_updated.scd".
                    scd_label = Path(st.scd_name or (scd_path.name if scd_path
                                                     else "arquivo.scd"))
                if rdb is None or scd_path is None:
                    self._send_json(409, {"error": "RDB ou SCD nao carregado"})
                    return
                entry = rdb_loader.find_gle(rdb, relay, gle)
                if entry is None or not entry.fs_path.is_file():
                    self._send_json(404, {"error": f"GLE nao encontrado: {relay}/{gle}"})
                    return
                try:
                    if direction == "scd-to-gle":
                        # The source RDB lives in the content cache, which
                        # is shared; the derived output belongs to this
                        # session (and /download only serves its dirs).
                        out_path = self.sdir("out") / _with_suffix_before_ext(
                            Path(rdb.display_name), "_comments_updated",
                        ).name
                        result = update_rdb_with_scd_descs(
                            rdb_path=rdb.rdb_path,
                            extract_dir=rdb.extract_dir,
                            relay_name=relay,
                            gle_name=gle,
                            gle_fs_path=entry.fs_path,
                            scd_path=scd_path,
                            ied_name=ied,
                            output_path=out_path,
                            job=self.job(),
                        )
                    else:  # gle-to-scd
                        # The source SCD can now also come from the project
                        # library (shared with the other tools in the same
                        # session); the derived output belongs to this tool
                        # (and /download only serves its directories).
                        out_path = self.sdir("out") / _with_suffix_before_ext(
                            scd_label, "_comments_updated",
                        ).name
                        result = update_scd_with_gle_comments(
                            scd_path=scd_path,
                            ied_name=ied,
                            gle_path=entry.fs_path,
                            output_path=out_path,
                        )
                except Exception as e:
                    logger.exception("falha aplicando %s: %s", direction, e)
                    self._send_json(500, {"error": str(e)})
                    return
                if result.get("ok"):
                    out_abs = Path(result["output_path"]).resolve()
                    # A corrected RDB or SCD is input for the other tools,
                    # so it enters the project library instead of dying in
                    # this tab's download link.
                    result["project_file"] = self.publish_output(
                        out_abs, "VB Updater", job=self.job(), logger=logger)
                    result["download_url"] = self.mount_prefix + "/download?file=" + quote(str(out_abs), safe="")
                    result["output_name"] = out_abs.name
                    logger.info("[vb-updater] apply %s -> %s", direction, out_abs.name)
                    self._send_json(200, result)
                else:
                    self._send_json(422, result)
                return

            if path == "/apply-batch":
                body = self.rfile.read(length) if length > 0 else b"{}"
                try:
                    payload = json.loads(body or b"{}")
                    selections = payload.get("selections", [])
                except (json.JSONDecodeError, TypeError):
                    self._send_json(400, {"error": "bad request"})
                    return
                if not isinstance(selections, list) or not selections:
                    self._send_json(400, {"error": "selections vazia"})
                    return
                with self.require_session().lock:
                    st = self.sess()
                    rdb = st.rdb
                    scd_path = st.scd_path
                if rdb is None or scd_path is None:
                    self._send_json(409, {"error": "RDB ou SCD nao carregado"})
                    return

                resolved: list[dict] = []
                invalid: list[dict] = []
                for sel in selections:
                    if not isinstance(sel, dict):
                        invalid.append({"error": "selecao invalida", "raw": str(sel)})
                        continue
                    relay = str(sel.get("relay", "")).strip()
                    ied = str(sel.get("ied", "")).strip()
                    gle = str(sel.get("gle", "")).strip()
                    if not (relay and ied and gle):
                        invalid.append({
                            "relay": relay, "ied": ied, "gle": gle,
                            "error": "campo obrigatorio ausente",
                        })
                        continue
                    entry = rdb_loader.find_gle(rdb, relay, gle)
                    if entry is None or not entry.fs_path.is_file():
                        invalid.append({
                            "relay": relay, "ied": ied, "gle": gle,
                            "error": "GLE nao encontrado",
                        })
                        continue
                    resolved.append({
                        "relay": relay, "ied": ied,
                        "gle_name": gle, "gle_fs_path": entry.fs_path,
                    })

                if not resolved:
                    self._send_json(422, {
                        "error": "nenhuma selecao valida",
                        "invalid": invalid,
                    })
                    return

                out_path = self.sdir("out") / _with_suffix_before_ext(
                    Path(rdb.display_name), "_batch_comments_updated",
                ).name
                try:
                    result = update_rdb_with_scd_descs_batch(
                        rdb_path=rdb.rdb_path,
                        extract_dir=rdb.extract_dir,
                        scd_path=scd_path,
                        selections=resolved,
                        output_path=out_path,
                        job=self.job(),
                    )
                except Exception as e:
                    logger.exception("falha aplicando batch: %s", e)
                    self._send_json(500, {"error": str(e)})
                    return

                if not result.get("ok"):
                    # All-or-nothing: no selection was written, so there is
                    # no file to download nor to publish into the library.
                    # The per-selection `results` go along so the screen can
                    # say WHICH one failed.
                    if invalid:
                        result["invalid"] = invalid
                    logger.warning("[vb-updater] apply-batch abortado: %s",
                                   result.get("error"))
                    self._send_json(422, result)
                    return

                out_abs = Path(result["output_path"]).resolve()
                result["project_file"] = self.publish_output(
                    out_abs, "VB Updater", job=self.job(), logger=logger)
                result["download_url"] = self.mount_prefix + "/download?file=" + quote(str(out_abs), safe="")
                result["output_name"] = out_abs.name
                if invalid:
                    result["invalid"] = invalid
                logger.info(
                    "[vb-updater] apply-batch (%d ok, %d fail) -> %s",
                    result.get("succeeded", 0), result.get("failed", 0),
                    out_abs.name,
                )
                self._send_json(200, result)
                return

            if path == "/export-descriptions":
                body = self.rfile.read(length) if length > 0 else b"{}"
                try:
                    payload = json.loads(body or b"{}")
                    selections = payload.get("selections", [])
                except (json.JSONDecodeError, TypeError):
                    self._send_json(400, {"error": "bad request"})
                    return
                if not isinstance(selections, list) or not selections:
                    self._send_json(400, {"error": "selections vazia"})
                    return
                with self.require_session().lock:
                    st = self.sess()
                    scd_path = st.scd_path
                    scd_label = Path(st.scd_name or (scd_path.name if scd_path
                                                     else "arquivo.scd"))
                if scd_path is None:
                    self._send_json(409, {"error": "SCD nao carregado"})
                    return
                # Collect IEDs preserving order and deduplicating. Also
                # maps IED -> relay name (RDB) to show on the sheet.
                ied_names: list[str] = []
                seen: set[str] = set()
                rdb_by_ied: dict[str, str] = {}
                for sel in selections:
                    if not isinstance(sel, dict):
                        continue
                    ied = str(sel.get("ied", "")).strip()
                    relay = str(sel.get("relay", "")).strip()
                    if not ied or ied in seen:
                        continue
                    seen.add(ied)
                    ied_names.append(ied)
                    if relay:
                        rdb_by_ied[ied] = relay
                if not ied_names:
                    self._send_json(400, {"error": "nenhum IED valido na selecao"})
                    return
                try:
                    xlsx_bytes = build_vb_descriptions_xlsx(
                        scd_path=scd_path, ied_names=ied_names,
                        rdb_by_ied=rdb_by_ied,
                    )
                except Exception as e:
                    logger.exception("falha gerando xlsx: %s", e)
                    self._send_json(500, {"error": str(e)})
                    return
                # Saves into the session's SCD dir (the /download sandbox).
                out_name = _with_suffix_before_ext(
                    scd_label, "_descriptions",
                ).with_suffix(".xlsx").name
                out_path = (self.sdir("scd") / out_name).resolve()
                try:
                    out_path.write_bytes(xlsx_bytes)
                except OSError as e:
                    self._send_json(500, {"error": f"falha ao salvar xlsx: {e}"})
                    return
                logger.info(
                    "[vb-updater] export-descriptions: %d IEDs -> %s",
                    len(ied_names), out_name,
                )
                self._send_json(200, {
                    "ok": True,
                    "output_name": out_name,
                    "project_file": self.publish_output(
                        out_path, "VB Updater", job=self.job(), logger=logger),
                    "download_url": self.mount_prefix + "/download?file=" + quote(str(out_path), safe=""),
                    "ied_count": len(ied_names),
                })
                return

            if path == "/import-descriptions":
                if length <= 0:
                    self._send_json(400, {"error": "empty upload"})
                    return
                if length > _SCD_MAX_BYTES:
                    self._send_json(413, {"error": "arquivo grande demais"})
                    return
                with self.require_session().lock:
                    st = self.sess()
                    scd_path = st.scd_path
                    scd_label = Path(st.scd_name or (scd_path.name if scd_path
                                                     else "arquivo.scd"))
                if scd_path is None:
                    self._send_json(409, {"error": "SCD nao carregado"})
                    return
                # Selected IEDs (optional filter): accepts the header
                # X-Selected-Ieds with a JSON list (URL-encoded). JSON and
                # not "a,b" because the client's encodeURIComponent escapes a
                # literal comma inside a name exactly like the separator:
                # after the unquote the two are indistinguishable and an IED
                # called "A,B" would become two.
                raw_sel = self.headers.get("X-Selected-Ieds", "")
                selected_ieds: set[str] | None = None
                if raw_sel:
                    try:
                        parsed_sel = json.loads(unquote(raw_sel))
                        if isinstance(parsed_sel, list):
                            selected_ieds = {
                                s.strip() for s in parsed_sel
                                if isinstance(s, str) and s.strip()
                            }
                    except Exception:
                        selected_ieds = None
                xlsx_bytes = self.rfile.read(length)
                try:
                    parsed = parse_vb_descriptions_xlsx(xlsx_bytes)
                except Exception as e:
                    logger.exception("falha parseando xlsx: %s", e)
                    self._send_json(422, {"error": f"xlsx invalido: {e}"})
                    return
                if not parsed:
                    self._send_json(422, {
                        "error": "nenhuma descricao valida encontrada no xlsx "
                                 "(verifique que A1='IED:' e B1=<nome do IED>)",
                    })
                    return
                # Filter by the selected ones, if any.
                ignored: list[str] = []
                if selected_ieds is not None:
                    filtered = {}
                    for ied, vb_map in parsed.items():
                        if ied in selected_ieds:
                            filtered[ied] = vb_map
                        else:
                            ignored.append(ied)
                    parsed = filtered
                if not parsed:
                    self._send_json(422, {
                        "error": "nenhum IED do xlsx esta na selecao atual",
                        "ignored_ieds": ignored,
                    })
                    return
                out_path = self.sdir("out") / _with_suffix_before_ext(
                    scd_label, "_descriptions_imported").name
                try:
                    result = update_scd_with_descriptions_multi(
                        scd_path=scd_path,
                        descriptions_by_ied=parsed,
                        output_path=out_path,
                    )
                except Exception as e:
                    logger.exception("falha aplicando descricoes: %s", e)
                    self._send_json(500, {"error": str(e)})
                    return
                out_abs = Path(result["output_path"]).resolve()
                result["project_file"] = self.publish_output(
                    out_abs, "VB Updater", job=self.job(), logger=logger)
                result["download_url"] = self.mount_prefix + "/download?file=" + quote(str(out_abs), safe="")
                result["output_name"] = out_abs.name
                if ignored:
                    result["ignored_ieds"] = ignored
                logger.info(
                    "[vb-updater] import-descriptions: %d IEDs aplicados -> %s",
                    len(parsed), out_abs.name,
                )
                self._send_json(200, result)
                return

            if path in ("/select-rdb", "/select-scd"):
                # The body of the old /rdb-upload or /scd-upload, from
                # `process_upload`/`load_scd` onward: the file was already
                # received and extracted/validated in /files/.
                want = (filelib.KIND_RDB if path == "/select-rdb"
                        else filelib.KIND_SCD)
                payload = self._read_json_body()
                sha = (payload.get("sha256") or "").strip()
                lib = filelib.library_for(sessions, self.require_session())
                with self.require_session().lock:
                    chosen = lib.get(sha)
                if chosen is None or chosen.kind != want:
                    self._send_json(404, {
                        "error": "Arquivo não está mais no projeto."})
                    return
                job = self.job()
                with self.require_session().lock:
                    st = self.sess()
                    if want == filelib.KIND_RDB:
                        st.rdb = chosen.require_rdb()
                        logger.info("[vb-updater] RDB '%s' (%s) escolhido; "
                                    "%d relé(s) com GLE",
                                    chosen.display_name, chosen.short_sha,
                                    len(chosen.require_rdb().relays))
                    else:
                        st.scd_path = chosen.scd_path
                        st.scd_name = chosen.display_name
                        logger.info("[vb-updater] SCD '%s' (%s) escolhido",
                                    chosen.display_name, chosen.short_sha)
                    # The RDB x SCD cross-match only happens when both
                    # exist; `maybe_match` already knows that.
                    job.stage("Cruzando RDB com SCD", 60)
                    maybe_match(st)
                job.finish("Arquivo carregado")
                self._send_json(200, state_payload(self.sess()))
                return

            self._send(404, "not found", "text/plain")

    return Handler
