"""Reading the GLE: pages, bits and analog symbols per page.

It came out of `dashboard.py` unchanged. It talks neither to a relay nor to
HTTP: it is only what the diagram needs to know about the file to build the
page strip, the `/values?page=` filter and the variable search index.
"""

from __future__ import annotations

import re

from selfiles.gle import element_info, is_const_symbol_name


def list_pages(gle_root) -> list[tuple[str, str]]:
    """Returns [(name, safe_id)]."""
    pages = []
    for p in gle_root.findall(".//page"):
        name = p.get("name", "")
        safe = re.sub(r"[^A-Za-z0-9_-]", "_", name) or f"page_{len(pages)}"
        pages.append((name, safe))
    return pages


def collect_bit_names(gle_root, relay_model=None) -> set[str]:
    """Every SYMBOL in the GLE that has a name (candidates for colouring).
    Constants (a literal numeric name) are excluded -- they do not exist in
    the relay's Relay Word, they are only setpoints/literals in the diagram.
    Analog SYMBOLs (AMV/PMV/MV/MAG/...) are excluded too: they carry a
    continuous value from the fast_meter, not a 0/1 bit of the Relay Word.
    """
    names = set()
    for el in gle_root.findall(".//element"):
        if el.get("type") != "SYMBOL":
            continue
        info = element_info(el)
        nm = info["name"]
        if not nm or is_const_symbol_name(nm):
            continue
        if relay_model is not None and relay_model.is_analog_symbol(nm):
            continue
        names.add(nm)
    return names


def collect_analog_symbols_per_page(gle_root, relay_model) -> dict[str, dict[str, str]]:
    """
    Map safe_page_id -> {NAME: GROUP_KEY}: analog SYMBOLs referenced on each
    page. Empty if relay_model has no analog_groups (models with no JSON, or
    a JSON with no analog_symbols).
    Used by /values to filter which analogs to deliver per page and by the JS
    to group the panel's 'Analogicos' section.
    """
    out: dict[str, dict[str, str]] = {}
    if relay_model is None or not relay_model.analog_groups:
        for p in gle_root.findall(".//page"):
            name = p.get("name", "")
            safe = re.sub(r"[^A-Za-z0-9_-]", "_", name) or f"page_{len(out)}"
            out[safe] = {}
        return out
    for p in gle_root.findall(".//page"):
        name = p.get("name", "")
        safe = re.sub(r"[^A-Za-z0-9_-]", "_", name) or f"page_{len(out)}"
        per: dict[str, str] = {}
        for el in p.findall(".//element"):
            if (el.get("type") or "") != "SYMBOL":
                continue
            info = element_info(el)
            raw = info.get("name") or ""
            if not raw or is_const_symbol_name(raw):
                continue
            grp = relay_model.analog_group_for(raw)
            if grp is not None:
                per[raw.upper()] = grp.key
        out[safe] = per
    return out


def collect_bits_per_page(gle_root, relay_model=None) -> dict[str, set[str]]:
    """
    Map safe_page_id -> set(names of the DIGITAL bits to poll on that page).

    Includes:
      - SYMBOLs (I/O and Relay Word signals) -- except numeric constants and
        except analog SYMBOLs (which carry a continuous value from the
        fast_meter, handled in collect_analog_symbols_per_page).
      - Bits derived from stateful blocks (PLT/PCNDTIMER/AST/PSV on the 4xx,
        LATCH/TIMER/COUNTER on the 7xx, etc.), generated by the model profile
        via `relay_model.derived_bit_for(xml_type, instance, name)`.

    If `relay_model` is None we generate no derived bits and do not filter
    analogs (named SYMBOLs only).
    """
    out = {}
    for p in gle_root.findall(".//page"):
        name = p.get("name", "")
        safe = re.sub(r"[^A-Za-z0-9_-]", "_", name) or f"page_{len(out)}"
        names = set()
        for el in p.findall(".//element"):
            t = el.get("type") or ""
            info = element_info(el)
            raw = info.get("name") or ""
            if t == "SYMBOL":
                if not raw:
                    continue
                # Constants (a literal numeric name) are not Relay Word bits
                # -- there is no point in asking the relay for them.
                if is_const_symbol_name(raw):
                    continue
                # Analogs leave the digital pool -- continuous value from FM.
                if relay_model is not None and relay_model.is_analog_symbol(raw):
                    continue
                names.add(raw.upper())
            elif relay_model is not None:
                # Stateful blocks (LATCH/TIMER/COUNTER, PLT/PCNDTIMER/AST/PSV...):
                # ask the model profile which derived bit there is, if any.
                le = el.find("logic_element")
                if le is None:
                    continue
                try:
                    inst = int(le.get("physical_instance_number") or 0)
                except ValueError:
                    inst = 0
                pname = le.get("physical_instance_name") or ""
                bit = relay_model.derived_bit_for(t, inst, pname)
                if bit:
                    names.add(bit.upper())
        out[safe] = names
    return out

